### ISSUE TITLE
GTKListBox+Rows.m compilation error

### ISSUE THREAD

**Issue by GunGraveKoga** [KyleCardoza/GTKKit#4]
In file included from ./src/GTKListBox+Rows.m:21:
./src/GTKListBox+Rows.h:44:60: error: interface type 'GTKWidget' cannot be passed by value; did you forget * in 'GTKWidget'?
- (void)setRowHeaderAtIndex:(int)index toWidget:(GTKWidget)header;
                                                           ^
                                                          *
./src/GTKListBox+Rows.m:37:60: error: interface type 'GTKWidget' cannot be passed by value; did you forget * in 'GTKWidget'?
- (void)setRowHeaderAtIndex:(int)index toWidget:(GTKWidget)header
                                                           ^
                                                          *
./src/GTKListBox+Rows.m:73:71: error: expected ';' after expression
  gtk_list_box_row_set_activatable(GTK_LIST_BOX_ROW(row), activatable)
                                                                      ^
                                                                      ;
3 errors generated.

**Comment by KyleCardoza** [comment]
I don't know if removing the file with the bug counts as fixing it, but that's what's happened.
